hyper_args:
  base_model: LinearRegressionRegressorMLModel
  base_models:
  - LinearRegressionRegressorMLModel
  - LinearRegressionRegressorMLModel
  - LinearRegressionRegressorMLModel
  - LinearRegressionRegressorMLModel
  - LinearRegressionRegressorMLModel
  - LinearRegressionRegressorMLModel
  - LinearRegressionRegressorMLModel
  - LinearRegressionRegressorMLModel
  - LinearRegressionRegressorMLModel
  - LinearRegressionRegressorMLModel
  - LinearRegressionRegressorMLModel
  - LinearRegressionRegressorMLModel
  - LinearRegressionRegressorMLModel
  - LinearRegressionRegressorMLModel
  - LinearRegressionRegressorMLModel
  - LinearRegressionRegressorMLModel
  - LinearRegressionRegressorMLModel
  - LinearRegressionRegressorMLModel
  - LinearRegressionRegressorMLModel
  - LinearRegressionRegressorMLModel
  - LinearRegressionRegressorMLModel
  - LinearRegressionRegressorMLModel
  - LinearRegressionRegressorMLModel
  - LinearRegressionRegressorMLModel
  - LinearRegressionRegressorMLModel
  - LinearRegressionRegressorMLModel
  - LinearRegressionRegressorMLModel
  - LinearRegressionRegressorMLModel
  - LinearRegressionRegressorMLModel
  - LinearRegressionRegressorMLModel
  data_task: OneStopL2_MICH
  data_tasks:
  - OneStopL2_LEX
  - OneStopL2_MICH
  - OneStopL2_MICH_R
  - OneStopL2_MICH_L
  - OneStopL2_TOE
  - OneStopL2_TOE_LR
  folds:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  gpu_count: 1
  model: LinearWpCoefsNoNormNoInterceptArgs
  models:
  - LinearRegressionArgs
  - LinearMeziereArgs
  - LinearFixationMetricsArgs
  - LinearSClustersArgs
  - LinearSClustersNoNormArgs
  - LinearWpCoefsArgs
  - LinearWpCoefsNoNormArgs
  - LinearWpCoefsNoInterceptArgs
  - LinearWpCoefsNoNormNoInterceptArgs
  - LinearReadingSpeedFixationMetricsArgs
  - LinearReadingSpeedSClustersArgs
  - LinearReadingSpeedSClustersNoNormArgs
  - LinearReadingSpeedWpCoefsArgs
  - LinearReadingSpeedWpCoefsNoNormArgs
  - LinearReadingSpeedWpCoefsNoInterceptArgs
  - LinearReadingSpeedWpCoefsNoNormNoInterceptArgs
  - LinearReadingSpeedFixationMetricsSClustersArgs
  - LinearReadingSpeedFixationMetricsSClustersNoNormArgs
  - LinearReadingSpeedFixationMetricsWpCoefsArgs
  - LinearReadingSpeedFixationMetricsWpCoefsNoNormArgs
  - LinearReadingSpeedFixationMetricsWpCoefsNoInterceptArgs
  - LinearReadingSpeedFixationMetricsWpCoefsNoNormNoInterceptArgs
  - LinearReadingSpeedSClustersWpCoefsArgs
  - LinearReadingSpeedSClustersNoNormWpCoefsNoNormArgs
  - LinearReadingSpeedSClustersWpCoefsNoInterceptArgs
  - LinearReadingSpeedSClustersNoNormWpCoefsNoNormNoInterceptArgs
  - LinearReadingSpeedFixationMetricsSClustersWpCoefsArgs
  - LinearReadingSpeedFixationMetricsSClustersNoNormWpCoefsNoNormArgs
  - LinearReadingSpeedFixationMetricsSClustersWpCoefsNoInterceptArgs
  - LinearReadingSpeedFixationMetricsSClustersNoNormWpCoefsNoNormNoInterceptArgs
  num_duplicates_per_gpu: 1
  run_cap: 250
  search_algorithm: grid
  slurm_cpus: 10
  slurm_mailto: shubi@campus.technion.ac.il
  slurm_mem: 75G
  trainer: TrainerML
  trainers:
  - TrainerML
  - TrainerML
  - TrainerML
  - TrainerML
  - TrainerML
  - TrainerML
  - TrainerML
  - TrainerML
  - TrainerML
  - TrainerML
  - TrainerML
  - TrainerML
  - TrainerML
  - TrainerML
  - TrainerML
  - TrainerML
  - TrainerML
  - TrainerML
  - TrainerML
  - TrainerML
  - TrainerML
  - TrainerML
  - TrainerML
  - TrainerML
  - TrainerML
  - TrainerML
  - TrainerML
  - TrainerML
  - TrainerML
  - TrainerML
  wandb_entity: EyeRead
  wandb_project: OneStopL2_linear
sweep_ids:
- jc57dqmt
- r4bfhwnb
- z60txscs
- jsw1e7pm
- i1kg5mqi
- nuhcvl7w
- 2fqrsha9
- 0sgwsuiz
- cw5jlmga
- o5i1xl6d
