#!/bin/bash

#SBATCH --job-name=LinearReadingSpeedWpCoefsArgs_OneStopL2_MICH_R-array
#SBATCH --output=logs/LinearReadingSpeedWpCoefsArgs_OneStopL2_MICH_R-%A_%a.out
#SBATCH --error=logs/LinearReadingSpeedWpCoefsArgs_OneStopL2_MICH_R-%A_%a.err
#SBATCH --partition=work,mig
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --gpus=1
#SBATCH --qos=normal
#SBATCH --cpus-per-task=10
#SBATCH --mem=75G
#SBATCH --array=0-9
#SBATCH --mail-type=ALL
#SBATCH --mail-user=shubi@campus.technion.ac.il

sweep_ids=(jvlypc3i 2es19prr a3ndm7bp vcu0nopx rf580ud8 k2d64tzg b9289vx3 z6ge9l2t 7pvqa4sb 8arhw3m5)
SWEEP_ID=${sweep_ids[$SLURM_ARRAY_TASK_ID]}


srun --overlap --ntasks=1 --nodes=1 --cpus-per-task=$SLURM_CPUS_PER_TASK -p work,mig \
    --container-image=/rg/berzak_prj/shubi/prj/rev05_pytorchlightning+pytorch_lightning.sqsh \
    --container-mounts="/rg/berzak_prj/shubi:/home/shubi" \
    --container-workdir=/home/shubi/eyebench_private \
    bash -c "
echo 'Starting job on $(date)'
source /home/shubi/prj/nvidia_pytorch_25_03_py3_mamba_wrapper.sh
conda activate eyebench
wandb agent EyeRead/OneStopL2_linear/$SWEEP_ID"
    
