#!/bin/bash

#SBATCH --job-name=LinearReadingSpeedSClustersArgs_OneStopL2_TOE-array
#SBATCH --output=logs/LinearReadingSpeedSClustersArgs_OneStopL2_TOE-%A_%a.out
#SBATCH --error=logs/LinearReadingSpeedSClustersArgs_OneStopL2_TOE-%A_%a.err
#SBATCH --partition=work,mig
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --gpus=1
#SBATCH --qos=normal
#SBATCH --cpus-per-task=10
#SBATCH --mem=75G
#SBATCH --array=0-9
#SBATCH --mail-type=ALL
#SBATCH --mail-user=shubi@campus.technion.ac.il

sweep_ids=(0kfoenzi 0m665zqp mlx12o53 k7xyq60r b3gbm8ht b115gv9c sglw4fza tbhz1ikc iwi9em6h paec7dg8)
SWEEP_ID=${sweep_ids[$SLURM_ARRAY_TASK_ID]}


srun --overlap --ntasks=1 --nodes=1 --cpus-per-task=$SLURM_CPUS_PER_TASK -p work,mig \
    --container-image=/rg/berzak_prj/shubi/prj/rev05_pytorchlightning+pytorch_lightning.sqsh \
    --container-mounts="/rg/berzak_prj/shubi:/home/shubi" \
    --container-workdir=/home/shubi/eyebench_private \
    bash -c "
echo 'Starting job on $(date)'
source /home/shubi/prj/nvidia_pytorch_25_03_py3_mamba_wrapper.sh
conda activate eyebench
wandb agent EyeRead/OneStopL2_linear/$SWEEP_ID"
    
