#!/bin/bash

#SBATCH --job-name=LinearWpCoefsNoNormArgs_OneStopL2_TOE_LR-array
#SBATCH --output=logs/LinearWpCoefsNoNormArgs_OneStopL2_TOE_LR-%A_%a.out
#SBATCH --error=logs/LinearWpCoefsNoNormArgs_OneStopL2_TOE_LR-%A_%a.err
#SBATCH --partition=work,mig
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --gpus=1
#SBATCH --qos=normal
#SBATCH --cpus-per-task=10
#SBATCH --mem=75G
#SBATCH --array=0-9
#SBATCH --mail-type=ALL
#SBATCH --mail-user=shubi@campus.technion.ac.il

sweep_ids=(abm0vrpr nvs0cxff r5yrvd7b 068u7poy nonq490m coviy63d 7g8c4t5y 8jn578o6 bbw8glr4 3ks1mu26)
SWEEP_ID=${sweep_ids[$SLURM_ARRAY_TASK_ID]}


srun --overlap --ntasks=1 --nodes=1 --cpus-per-task=$SLURM_CPUS_PER_TASK -p work,mig \
    --container-image=/rg/berzak_prj/shubi/prj/rev05_pytorchlightning+pytorch_lightning.sqsh \
    --container-mounts="/rg/berzak_prj/shubi:/home/shubi" \
    --container-workdir=/home/shubi/eyebench_private \
    bash -c "
echo 'Starting job on $(date)'
source /home/shubi/prj/nvidia_pytorch_25_03_py3_mamba_wrapper.sh
conda activate eyebench
wandb agent EyeRead/OneStopL2_linear/$SWEEP_ID"
    
