#!/bin/bash

#SBATCH --job-name=RoberteyeFixation_OneStop_RC-array
#SBATCH --output=logs/RoberteyeFixation_OneStop_RC-%A_%a.out
#SBATCH --error=logs/RoberteyeFixation_OneStop_RC-%A_%a.err
#SBATCH --partition=work
#SBATCH --ntasks=1
#SBATCH --nodes=1

#SBATCH --qos=basic
#SBATCH --cpus-per-task=10
#SBATCH --mem=75G
#SBATCH --array=0-9
#SBATCH --mail-type=ALL
#SBATCH --mail-user=shubi@campus.technion.ac.il

sweep_ids=(2p2mnqc7 ebchyz7v y25cv9ng 6tfqps7b 5der57r7 yzpz1glr dql3gg8z somjbf3a 4gz4nswb eq8msrfh)
SWEEP_ID=${sweep_ids[$SLURM_ARRAY_TASK_ID]}


srun --overlap --ntasks=1 --nodes=1 --cpus-per-task=$SLURM_CPUS_PER_TASK -p work \
    --container-image=/rg/berzak_prj/shubi/prj/rev05_pytorchlightning+pytorch_lightning.sqsh \
    --container-mounts="/rg/berzak_prj/shubi:/home/shubi" \
    --container-workdir=/home/shubi/eyebench_private \
    bash -c "
echo 'Starting job on $(date)'
source /home/shubi/prj/nvidia_pytorch_25_03_py3_mamba_wrapper.sh
conda activate prof_env
wandb agent EyeRead/OneStop_RC_20251118/$SWEEP_ID"
    
