#!/bin/bash

#SBATCH --job-name=LinearReadingSpeedFixationMetricsSClustersNoNormArgs_OneStopL2_MICH_R-array
#SBATCH --output=logs/LinearReadingSpeedFixationMetricsSClustersNoNormArgs_OneStopL2_MICH_R-%A_%a.out
#SBATCH --error=logs/LinearReadingSpeedFixationMetricsSClustersNoNormArgs_OneStopL2_MICH_R-%A_%a.err
#SBATCH --partition=work,mig
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --gpus=1
#SBATCH --qos=basic
#SBATCH --cpus-per-task=10
#SBATCH --mem=75G
#SBATCH --array=0-9
#SBATCH --mail-type=ALL
#SBATCH --mail-user=shubi@campus.technion.ac.il

sweep_ids=(39x1gqic 7sttyllq 2ss1gy2g 0usndnjk 003qbbh5 239cnvxs zbdma6oo 6jshf6nu fgmo7qt0 yy54mvwj)
SWEEP_ID=${sweep_ids[$SLURM_ARRAY_TASK_ID]}


srun --overlap --ntasks=1 --nodes=1 --cpus-per-task=$SLURM_CPUS_PER_TASK -p work,mig \
    --container-image=/rg/berzak_prj/shubi/prj/rev05_pytorchlightning+pytorch_lightning.sqsh \
    --container-mounts="/rg/berzak_prj/shubi:/home/shubi" \
    --container-workdir=/home/shubi/eyebench_private \
    bash -c "
echo 'Starting job on $(date)'
source /home/shubi/prj/nvidia_pytorch_25_03_py3_mamba_wrapper.sh
conda activate eyebench
wandb agent EyeRead/OneStopL2_linear/$SWEEP_ID"
    
