hyper_args:
  accelerator: cpu
  base_model: MAGModel
  base_models:
  - AhnCNNModel
  - AhnRNNModel
  - BEyeLSTMModel
  - PLMASModel
  - MAGModel
  - PLMASFModel
  - PostFusionModel
  - Roberteye
  - Roberteye
  - Roberteye
  - SupportVectorMachineMLModel
  - XGBoostMLModel
  - RandomForestMLModel
  - LogisticRegressionMLModel
  - LogisticRegressionMLModel
  - DummyClassifierMLModel
  cpu_count: 42
  data_task: OneStop_RC
  data_tasks:
  - OneStop_RC
  folds:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  gpu_count: 1
  model: MAG
  models:
  - AhnCNN
  - AhnRNN
  - BEyeLSTMArgs
  - PLMASArgs
  - MAG
  - PLMASfArgs
  - PostFusion
  - Roberta
  - RoberteyeFixation
  - RoberteyeWord
  - SupportVectorMachineMLArgs
  - XGBoostMLArgs
  - RandomForestMLArgs
  - LogisticRegressionMLArgs
  - LogisticMeziereArgs
  - DummyClassifierMLArgs
  num_duplicates_per_gpu: 1
  run_cap: 1000
  search_algorithm: grid
  slurm_cpus: 10
  slurm_mailto: shubi@campus.technion.ac.il
  slurm_mem: 75G
  trainer: TrainerDL
  trainers:
  - TrainerDL
  - TrainerDL
  - TrainerDL
  - TrainerDL
  - TrainerDL
  - TrainerDL
  - TrainerDL
  - TrainerDL
  - TrainerDL
  - TrainerDL
  - TrainerML
  - TrainerML
  - TrainerML
  - TrainerML
  - TrainerML
  - TrainerML
  wandb_entity: EyeRead
  wandb_project: OneStop_RC_20251118
sweep_ids:
- 369y2yte
- na141z2l
- 1qi2g7cc
- 4jqw4a3r
- o1av5aa7
- 6z9hy9e7
- qvlnri4h
- 84yi6rmu
- 4tkmkhp5
- eagm37a1
