hyper_args:
  accelerator: cpu
  base_model: RandomForestMLModel
  base_models:
  - AhnCNNModel
  - AhnRNNModel
  - BEyeLSTMModel
  - PLMASModel
  - MAGModel
  - PLMASFModel
  - PostFusionModel
  - Roberteye
  - Roberteye
  - Roberteye
  - SupportVectorMachineMLModel
  - XGBoostMLModel
  - RandomForestMLModel
  - LogisticRegressionMLModel
  - LogisticRegressionMLModel
  - DummyClassifierMLModel
  cpu_count: 42
  data_task: OneStop_RC
  data_tasks:
  - OneStop_RC
  folds:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  gpu_count: 1
  model: RandomForestMLArgs
  models:
  - AhnCNN
  - AhnRNN
  - BEyeLSTMArgs
  - PLMASArgs
  - MAG
  - PLMASfArgs
  - PostFusion
  - Roberta
  - RoberteyeFixation
  - RoberteyeWord
  - SupportVectorMachineMLArgs
  - XGBoostMLArgs
  - RandomForestMLArgs
  - LogisticRegressionMLArgs
  - LogisticMeziereArgs
  - DummyClassifierMLArgs
  num_duplicates_per_gpu: 1
  run_cap: 1000
  search_algorithm: grid
  slurm_cpus: 10
  slurm_mailto: shubi@campus.technion.ac.il
  slurm_mem: 75G
  trainer: TrainerML
  trainers:
  - TrainerDL
  - TrainerDL
  - TrainerDL
  - TrainerDL
  - TrainerDL
  - TrainerDL
  - TrainerDL
  - TrainerDL
  - TrainerDL
  - TrainerDL
  - TrainerML
  - TrainerML
  - TrainerML
  - TrainerML
  - TrainerML
  - TrainerML
  wandb_entity: EyeRead
  wandb_project: OneStop_RC_20251118
sweep_ids:
- dccrfihh
- m2zfaivz
- fszvwxtc
- sq0v73mn
- 5zvt0n3r
- lhg8d9zd
- i9247k60
- g5febl1s
- xkrxznaa
- 7vwqqmly
