hyper_args:
  accelerator: cpu
  base_model: Roberteye
  base_models:
  - AhnCNNModel
  - AhnRNNModel
  - BEyeLSTMModel
  - PLMASModel
  - MAGModel
  - PLMASFModel
  - PostFusionModel
  - Roberteye
  - Roberteye
  - Roberteye
  - SupportVectorMachineMLModel
  - XGBoostMLModel
  - RandomForestMLModel
  - LogisticRegressionMLModel
  - LogisticRegressionMLModel
  - DummyClassifierMLModel
  cpu_count: 42
  data_task: OneStop_RC
  data_tasks:
  - OneStop_RC
  folds:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  gpu_count: 1
  model: RoberteyeFixation
  models:
  - AhnCNN
  - AhnRNN
  - BEyeLSTMArgs
  - PLMASArgs
  - MAG
  - PLMASfArgs
  - PostFusion
  - Roberta
  - RoberteyeFixation
  - RoberteyeWord
  - SupportVectorMachineMLArgs
  - XGBoostMLArgs
  - RandomForestMLArgs
  - LogisticRegressionMLArgs
  - LogisticMeziereArgs
  - DummyClassifierMLArgs
  num_duplicates_per_gpu: 1
  run_cap: 1000
  search_algorithm: grid
  slurm_cpus: 10
  slurm_mailto: shubi@campus.technion.ac.il
  slurm_mem: 75G
  trainer: TrainerDL
  trainers:
  - TrainerDL
  - TrainerDL
  - TrainerDL
  - TrainerDL
  - TrainerDL
  - TrainerDL
  - TrainerDL
  - TrainerDL
  - TrainerDL
  - TrainerDL
  - TrainerML
  - TrainerML
  - TrainerML
  - TrainerML
  - TrainerML
  - TrainerML
  wandb_entity: EyeRead
  wandb_project: OneStop_RC_20251118
sweep_ids:
- 2p2mnqc7
- ebchyz7v
- y25cv9ng
- 6tfqps7b
- 5der57r7
- yzpz1glr
- dql3gg8z
- somjbf3a
- 4gz4nswb
- eq8msrfh
