hyper_args:
  accelerator: cpu
  base_model: SupportVectorMachineMLModel
  base_models:
  - AhnCNNModel
  - AhnRNNModel
  - BEyeLSTMModel
  - PLMASModel
  - MAGModel
  - PLMASFModel
  - PostFusionModel
  - Roberteye
  - Roberteye
  - Roberteye
  - SupportVectorMachineMLModel
  - XGBoostMLModel
  - RandomForestMLModel
  - LogisticRegressionMLModel
  - LogisticRegressionMLModel
  - DummyClassifierMLModel
  cpu_count: 42
  data_task: OneStop_RC
  data_tasks:
  - OneStop_RC
  folds:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  gpu_count: 1
  model: SupportVectorMachineMLArgs
  models:
  - AhnCNN
  - AhnRNN
  - BEyeLSTMArgs
  - PLMASArgs
  - MAG
  - PLMASfArgs
  - PostFusion
  - Roberta
  - RoberteyeFixation
  - RoberteyeWord
  - SupportVectorMachineMLArgs
  - XGBoostMLArgs
  - RandomForestMLArgs
  - LogisticRegressionMLArgs
  - LogisticMeziereArgs
  - DummyClassifierMLArgs
  num_duplicates_per_gpu: 1
  run_cap: 1000
  search_algorithm: grid
  slurm_cpus: 10
  slurm_mailto: shubi@campus.technion.ac.il
  slurm_mem: 75G
  trainer: TrainerML
  trainers:
  - TrainerDL
  - TrainerDL
  - TrainerDL
  - TrainerDL
  - TrainerDL
  - TrainerDL
  - TrainerDL
  - TrainerDL
  - TrainerDL
  - TrainerDL
  - TrainerML
  - TrainerML
  - TrainerML
  - TrainerML
  - TrainerML
  - TrainerML
  wandb_entity: EyeRead
  wandb_project: OneStop_RC_20251118
sweep_ids:
- ypky4mo8
- 4j9pbru9
- 2jth7bb6
- mco3mwap
- cyp3wi93
- 1n3w47om
- pgv9f5uk
- qfnfl5hn
- 46oqchca
- 2hff7gxp
