#!/bin/bash

#SBATCH --job-name=LinearReadingSpeedSClustersWpCoefsNoInterceptArgs_OneStopL2_MICH_L-array
#SBATCH --output=logs/LinearReadingSpeedSClustersWpCoefsNoInterceptArgs_OneStopL2_MICH_L-%A_%a.out
#SBATCH --error=logs/LinearReadingSpeedSClustersWpCoefsNoInterceptArgs_OneStopL2_MICH_L-%A_%a.err
#SBATCH --partition=work,mig
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --gpus=1
#SBATCH --qos=basic
#SBATCH --cpus-per-task=10
#SBATCH --mem=75G
#SBATCH --array=0-9
#SBATCH --mail-type=ALL
#SBATCH --mail-user=shubi@campus.technion.ac.il

sweep_ids=(m2ruzune 0hhyk4n6 j835x3zf 6v9alrq6 wyhnsamr oy8t1luq jx0ww03t k5yqydek h9d9v2j2 e1px67nl)
SWEEP_ID=${sweep_ids[$SLURM_ARRAY_TASK_ID]}


srun --overlap --ntasks=1 --nodes=1 --cpus-per-task=$SLURM_CPUS_PER_TASK -p work,mig \
    --container-image=/rg/berzak_prj/shubi/prj/rev05_pytorchlightning+pytorch_lightning.sqsh \
    --container-mounts="/rg/berzak_prj/shubi:/home/shubi" \
    --container-workdir=/home/shubi/eyebench_private \
    bash -c "
echo 'Starting job on $(date)'
source /home/shubi/prj/nvidia_pytorch_25_03_py3_mamba_wrapper.sh
conda activate eyebench
wandb agent EyeRead/OneStopL2_linear/$SWEEP_ID"
    
