#!/bin/bash

#SBATCH --job-name=LinearReadingSpeedFixationMetricsArgs_OneStopL2_TOE-array
#SBATCH --output=logs/LinearReadingSpeedFixationMetricsArgs_OneStopL2_TOE-%A_%a.out
#SBATCH --error=logs/LinearReadingSpeedFixationMetricsArgs_OneStopL2_TOE-%A_%a.err
#SBATCH --partition=work,mig
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --gpus=1
#SBATCH --qos=normal
#SBATCH --cpus-per-task=10
#SBATCH --mem=75G
#SBATCH --array=0-9
#SBATCH --mail-type=ALL
#SBATCH --mail-user=shubi@campus.technion.ac.il

sweep_ids=(orrnc9so hh7g5th5 en8qz61b qx903wgd rwa5dnen 782zrl0h 5wa504oz jere81rs a5zqybm4 bwk4ds9v)
SWEEP_ID=${sweep_ids[$SLURM_ARRAY_TASK_ID]}


srun --overlap --ntasks=1 --nodes=1 --cpus-per-task=$SLURM_CPUS_PER_TASK -p work,mig \
    --container-image=/rg/berzak_prj/shubi/prj/rev05_pytorchlightning+pytorch_lightning.sqsh \
    --container-mounts="/rg/berzak_prj/shubi:/home/shubi" \
    --container-workdir=/home/shubi/eyebench_private \
    bash -c "
echo 'Starting job on $(date)'
source /home/shubi/prj/nvidia_pytorch_25_03_py3_mamba_wrapper.sh
conda activate eyebench
wandb agent EyeRead/OneStopL2_linear/$SWEEP_ID"
    
