#!/bin/bash

#SBATCH --job-name=LinearReadingSpeedWpCoefsNoNormNoInterceptArgs_OneStopL2_TOE-array
#SBATCH --output=logs/LinearReadingSpeedWpCoefsNoNormNoInterceptArgs_OneStopL2_TOE-%A_%a.out
#SBATCH --error=logs/LinearReadingSpeedWpCoefsNoNormNoInterceptArgs_OneStopL2_TOE-%A_%a.err
#SBATCH --partition=work,mig
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --gpus=1
#SBATCH --qos=basic
#SBATCH --cpus-per-task=10
#SBATCH --mem=75G
#SBATCH --array=0-9
#SBATCH --mail-type=ALL
#SBATCH --mail-user=shubi@campus.technion.ac.il

sweep_ids=(ulg5lq67 6mkv1h69 2sv9gwys 9kzi2i1a yupa9x66 4jd058d4 rudj7w4w 968iihkk 2v83efbx 3jrl1o7t)
SWEEP_ID=${sweep_ids[$SLURM_ARRAY_TASK_ID]}


srun --overlap --ntasks=1 --nodes=1 --cpus-per-task=$SLURM_CPUS_PER_TASK -p work,mig \
    --container-image=/rg/berzak_prj/shubi/prj/rev05_pytorchlightning+pytorch_lightning.sqsh \
    --container-mounts="/rg/berzak_prj/shubi:/home/shubi" \
    --container-workdir=/home/shubi/eyebench_private \
    bash -c "
echo 'Starting job on $(date)'
source /home/shubi/prj/nvidia_pytorch_25_03_py3_mamba_wrapper.sh
conda activate eyebench
wandb agent EyeRead/OneStopL2_linear/$SWEEP_ID"
    
