#!/bin/bash

#SBATCH --job-name=RoberteyeWord_OneStop_RC-array
#SBATCH --output=logs/RoberteyeWord_OneStop_RC-%A_%a.out
#SBATCH --error=logs/RoberteyeWord_OneStop_RC-%A_%a.err
#SBATCH --partition=work
#SBATCH --ntasks=1
#SBATCH --nodes=1

#SBATCH --qos=basic
#SBATCH --cpus-per-task=10
#SBATCH --mem=75G
#SBATCH --array=0-9
#SBATCH --mail-type=ALL
#SBATCH --mail-user=shubi@campus.technion.ac.il

sweep_ids=(a1dgza08 11bk8wtp g4wakxj9 569axjmy e1m1glau 3r31up5b hho8knsv ni44bl2z c59u2ajy tqc9pp4i)
SWEEP_ID=${sweep_ids[$SLURM_ARRAY_TASK_ID]}


srun --overlap --ntasks=1 --nodes=1 --cpus-per-task=$SLURM_CPUS_PER_TASK -p work \
    --container-image=/rg/berzak_prj/shubi/prj/rev05_pytorchlightning+pytorch_lightning.sqsh \
    --container-mounts="/rg/berzak_prj/shubi:/home/shubi" \
    --container-workdir=/home/shubi/eyebench_private \
    bash -c "
echo 'Starting job on $(date)'
source /home/shubi/prj/nvidia_pytorch_25_03_py3_mamba_wrapper.sh
conda activate prof_env
wandb agent EyeRead/OneStop_RC_20251118/$SWEEP_ID"
    
